# Generated by Django 3.2.15 on 2022-12-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0003_auto_20221117_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitutions',
            name='educationalInstitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.educationalinstitution'),
        ),
        migrations.AlterField(
            model_name='gradeeducationalinstitutions',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='studentGradeEducationalInstitutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.studenttageducationalinstitutions'),
        ),
        migrations.AlterField(
            model_name='studenttageducationalinstitutions',
            name='gradeEducationalInstitutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.gradeeducationalinstitutions'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacherTagEducationalInstitutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.teachertageducationalinstitutions'),
        ),
        migrations.AlterField(
            model_name='teachertageducationalinstitutions',
            name='gradeEducationalInstitutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.gradeeducationalinstitutions'),
        ),
    ]
