# Generated by Django 3.2.15 on 2022-12-14 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lektorium_main', '0004_loggedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedin',
            options={'verbose_name': 'вход на платформу', 'verbose_name_plural': 'записи входа на платформу'},
        ),
        migrations.CreateModel(
            name='StudentStatisticsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('module_type', models.CharField(max_length=32, verbose_name='Module type')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
