# Generated by Django 3.2.15 on 2022-12-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0007_auto_20221214_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalinstitution',
            name='schoolName',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование школы'),
        ),
    ]
