# Generated by Django 3.2.15 on 2022-12-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0007_studentstatisticsitem_student_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatisticsitem',
            name='block_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='block_id'),
        ),
        migrations.AddField(
            model_name='studentstatisticsitem',
            name='block_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='block_type'),
        ),
        migrations.AddField(
            model_name='studentstatisticsitem',
            name='course_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='course_key'),
        ),
    ]
