# Generated by Django 3.2.15 on 2022-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lektorium_main', '0010_alter_statusmessage_status_type',),
        ('lektorium_main', '0008_auto_20221214_1522',),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatisticsitem',
            name='done',
            field=models.NullBooleanField(verbose_name='Done'),
        ),
    ]
