# Generated by Django 3.2.15 on 2022-12-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0011_studentstatisticsitem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedin',
            name='profile_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='id профиля пользователя в системе Educont'),
        ),
        migrations.AddField(
            model_name='studentstatisticsitem',
            name='profile_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='id профиля пользователя в системе Educont'),
        ),
    ]
