# Generated by Django 3.2.15 on 2022-12-20 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0012_auto_20221216_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cok',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИД курса на едх'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default=uuid.UUID('fc27eecb-5fc6-452a-8fc6-74d19fc0a9d2'), max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='externalId',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lektorium_main.tagcategory'),
        ),
    ]
