# Generated by Django 3.2.15 on 2022-12-20 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0013_auto_20221220_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatisticsitem',
            name='profile_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='id профиля пользователя в системе Educont'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
