# Generated by Django 3.2.15 on 2022-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0015_auto_20221220_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatisticsitem',
            name='profile_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='id профиля пользователя в системе Educont'),
        ),
    ]
