# Generated by Django 3.2.15 on 2022-12-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0017_auto_20221220_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lektorium_main.course')),
                ('externalLink', models.URLField(verbose_name='Ссылка в системе-источнике')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
            bases=('lektorium_main.course',),
        ),
        migrations.AlterModelOptions(
            name='cok',
            options={'verbose_name': 'курс ЦОК', 'verbose_name_plural': 'курсы ЦОК'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'раздел курса', 'verbose_name_plural': 'разделы курса'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='modified',
        ),
        migrations.DeleteModel(
            name='EducationalCourse',
        ),
        migrations.AddField(
            model_name='teachingmaterial',
            name='externalParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_materials', to='lektorium_main.course'),
        ),
        migrations.AddField(
            model_name='teachingmaterial',
            name='tags',
            field=models.ManyToManyField(to='lektorium_main.Tag'),
        ),
    ]
