# Generated by Django 3.2.15 on 2022-12-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0018_auto_20221221_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseTypeId',
        ),
    ]
