# Generated by Django 3.2.15 on 2022-12-21 04:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0019_remove_course_coursetypeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstatisticsitem',
            options={'verbose_name': 'запись статистики', 'verbose_name_plural': 'записи статистики'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name': 'категория тегов', 'verbose_name_plural': 'категории тегов'},
        ),
        migrations.AlterField(
            model_name='cok',
            name='grades',
            field=django_mysql.models.SetCharField(models.PositiveSmallIntegerField(), blank=True, max_length=23, size=16, verbose_name='Массив классов, которым доступен учебный материал'),
        ),
    ]
