# Generated by Django 3.2.15 on 2022-12-21 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lektorium_main', '0020_auto_20221221_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_profile_educont', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='section',
            name='externalParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lektorium_main.cok'),
        ),
        migrations.AlterField(
            model_name='studentstatisticsitem',
            name='profile_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='id профиля пользователя в системе Educont'),
        ),
    ]
