# Generated by Django 3.2.15 on 2022-12-21 22:00

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0021_auto_20221221_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='cok',
            name='tags',
            field=models.ManyToManyField(to='lektorium_main.Tag', verbose_name='Теги'),
        ),
    ]
