# Generated by Django 3.2.15 on 2022-12-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0022_auto_20221221_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachingmaterial',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
