# Generated by Django 3.2.15 on 2022-12-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0023_auto_20221221_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmaterial',
            name='externalLink',
            field=models.URLField(max_length=1024, verbose_name='Ссылка в системе-источнике'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('externalParent', 'order')},
        ),
    ]
