# Generated by Django 3.2.15 on 2022-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0024_auto_20221222_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cok',
            name='courseImageFile',
            field=models.ImageField(help_text='Изображение не должно содержать никаких надписей. Разрешение - 600x600 пикселей (допускается 500х500). Формат – jpg, jpeg, png. Размер – не более 5Мб.', upload_to='lektorium/course_images/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='cok',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ИД курса на едх'),
        ),
    ]
