# Generated by Django 3.2.15 on 2022-12-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0027_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatisticsitem',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
