# Generated by Django 3.2.15 on 2022-12-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0028_alter_studentstatisticsitem_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducontStatisticsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statisticType', models.CharField(choices=[('s', 'ENTER_TO_STUDY_SUBJECT'), ('e', 'ENTER_TO_EDUCATION_PLATFORM')], max_length=2, verbose_name='statisticType')),
                ('externalId', models.CharField(max_length=255, verbose_name='externalId')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('profile_id', models.UUIDField(verbose_name='id профиля пользователя в системе Educont')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
