# Generated by Django 3.2.15 on 2022-12-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0029_educontstatisticsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatisticsitem',
            name='student_module',
        ),
        migrations.RemoveField(
            model_name='studentstatisticsitem',
            name='user',
        ),
        migrations.RenameField(
            model_name='educontstatisticsitem',
            old_name='profile_id',
            new_name='profileId',
        ),
        migrations.AlterField(
            model_name='educontstatisticsitem',
            name='externalId',
            field=models.CharField(default='', max_length=255, verbose_name='externalId'),
        ),
        migrations.AlterField(
            model_name='educontstatisticsitem',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='LoggedIn',
        ),
        migrations.DeleteModel(
            name='StudentStatisticsItem',
        ),
    ]
