# Generated by Django 3.2.15 on 2022-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0031_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalinstitution',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educationalinstitutions',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gradeeducationalinstitutions',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statusmessage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenttageducationalinstitutions',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teachertageducationalinstitutions',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cok',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lektorium_main.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='teachingmaterial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lektorium_main.Tag'),
        ),
    ]
