# Generated by Django 3.2.15 on 2022-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0032_auto_20221226_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinstitution',
            name='municipalArea',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Муниципальный район образовательной организации'),
        ),
    ]
