# Generated by Django 3.2.15 on 2022-12-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0034_auto_20221227_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
