# Generated by Django 3.2.20 on 2023-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lektorium_main', '0036_auto_20221229_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TildaArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilda_content', models.TextField(blank=True, verbose_name='HTML-код')),
                ('styles', models.TextField(blank=True, verbose_name='Стили')),
                ('scripts', models.TextField(blank=True, verbose_name='Скрипты')),
                ('archive', models.FileField(blank=True, null=True, upload_to='tilda/zip/', verbose_name='Импорт из файла')),
                ('course_id', models.CharField(blank=True, help_text='Вставляем без пробелов. Пример: course-v1:edX+DemoX+Demo_Course', max_length=300, unique=True, verbose_name='Id курса')),
            ],
            options={
                'verbose_name': 'статья (Тильда)',
                'verbose_name_plural': 'статьи (Тильда)',
            },
        ),
    ]
